version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mongo-rs-backup"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/caddy-backup"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"

  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/grafana-backup"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"

  - package-ecosystem: "docker"
    directory: "/telegraf"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
