name: Deploy Infra

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  DOCKER_STACK_NAME: infra
  HOST: ${{ vars.HOST }}
  OWNER_NAME: vovastelmashchuk
  ROOT_SSH_PRIVATE_KEY: ${{ secrets.ROOT_SSH_PRIVATE_KEY }}
  ADMIN_USER: ${{ vars.ADMIN_USER }}
  USERNAME: ${{ vars.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - name: mongo-rs-backup
            context: ./mongo-rs-backup
            image: mongo-rs-backup
          - name: caddy
            context: ./caddy
            image: caddy
          - name: caddy-backup
            context: ./caddy-backup
            image: caddy-backup
          - name: grafana
            context: ./grafana
            image: grafana
          - name: grafana-backup
            context: ./grafana-backup
            image: grafana-backup
          - name: telegraf
            context: ./telegraf
            image: telegraf
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ matrix.image }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ matrix.image }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create env file
        run: |
            {
              echo "GIT_COMMIT_SHA=${{ github.sha }}"
              echo "MONGO_URI=${{ secrets.MONGO_URI }}"
              echo "USERNAME=${{ env.USERNAME }}"
              echo "PASSWORD=${{ env.PASSWORD }}"
              echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}"
              echo "S3_ACCESS_KEY_ID=${{ vars.S3_ACCESS_KEY_ID }}"
              echo "S3_ENDPOINT=${{ vars.S3_ENDPOINT }}"
              echo "MONGO_RS_ROOT_USERNAME=${{ vars.MONGO_RS_ROOT_USERNAME }}"
              echo "MONGO_RS_ROOT_PASSWORD=${{ secrets.MONGO_RS_ROOT_PASSWORD }}"
              echo "MONGO_RS_URI=${{ secrets.MONGO_RS_URI }}"
              echo "MONGO_RS_KEYFILE_CONTENT=${{ secrets.MONGO_RS_KEYFILE_CONTENT }}"
              echo "OWNER_NAME=${{ env.OWNER_NAME }}"
              echo "MONGO_NU_31_URI=${{ secrets.MONGO_NU_31_URI }}"
              echo "MONGO_NU31_VIEWER_USER=${{ vars.MONGO_NU31_VIEWER_USER }}"
              echo "MONGO_NU31_VIEWER_PASS=${{ secrets.MONGO_NU31_VIEWER_PASS }}"
            } > ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ${{ env.DOCKER_STACK_NAME }}
          file: docker-stack.yml
          host: ${{ env.HOST }}
          user: ${{ env.USERNAME }}
          ssh_key: ${{ env.ROOT_SSH_PRIVATE_KEY }}
          env_file: ./envfile